---
title: "Rubric for Oral Exams"
output:
  pdf_document: default
  html_document: default
---

Score   | Demonstration
--------|--------------
4       | __Excellent__ -- Outstanding ability to articulate the concepts covered in the exam, with comprehensive and thoughtful understanding of the content of the assessment. Few if if any errors occur. Any errors that do occur are minor and do not cloud the understanding articulated during the exam.  
        |     
3       | __Good__ -- Ability to articulate the central concepts covered in the exam, but several errors may occur during the assessment. These errors, however, do not cloud the central concepts of the assessment. 
        |    
2       | __Fair__ -- Limited ability to articulate the concepts covered in the exam, explanations contain inconsistencies and demonstrate limited understanding of the content.  
        |    
1       | __Poor__ -- Little to no articulation of concepts covered in the exam, numerous inconsistencies and errors occur and demonstrate little to no understanding of the content. 
        |    
0       | __No credit__ -- Inability to present any understanding of topics covered in exam. 


</br>
</br>

Letter grades will be assigned according to the following scale. In this scale
the first score comes from the first bank of questions and the second
score comes from the second bank of questions. Note that the first question 
is weighed more heavily than the second question. 

- 4, 4, (A+) 
- 4, 3 (A)
- 4, 2 (B-)
- 3, 4 (A-)
- 3, 3 (B)
- 3, 2 (B-)
- 2, 4 (C+)
- 2, 3 (C)
- 2, 2 (C-)
- earning a 1 on either question (at most a D+)
- earning a 0 on either question (F)
